# Generated by Django 4.0.3 on 2022-04-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='finished',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='order',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='url',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
